### ISSUE TITLE
Bank passbook

### ISSUE THREAD

**Issue by nerdyk3** [essentiasoftserv/openbharatocr#28]
Requirements

1. add a new function over the package that helps to parse bank passbook frontpage
2. the response will be in dict
3. dict must be with cif_no, name, account_no, address, phone, email, nomination_name, branch_name, bank_name,date_of_issue.
Input
image of the front page 

```
 {
 "name":"",
"cif_no":"",
"account_no":"",
"address":"",
"phone":"",
"email":"",
"nomination_name":"",
"branch_name":"",
"bank_name":"",
"date_of_issue":"",
}
```

**Comment by Rishabh0411** [comment]
Hey, I am currently working on it.

**Comment by Rishabh0411** [comment]
Hi , I have added a PR for the same
https://github.com/essentiasoftserv/openbharatocr/pull/38
