### ISSUE TITLE
Degree certificate

### ISSUE THREAD

**Issue by nerdyk3** [essentiasoftserv/openbharatocr#29]
Requirements

1. add a new function over the package that helps to parse university/college Degree 
2. the response will be in dict
3. dict must be with Name, degree name, university name, year of passing

Input
image of the degree
```
 {
 "name":"",
"degree_name":"",
"university_name":"",
"year_of_passing":""
}
```

**Comment by Rishabh0411** [comment]
Here's the for this issues's PR: 
https://github.com/essentiasoftserv/openbharatocr/pull/42
