### ISSUE TITLE
PAN OCR Not working properly

### ISSUE THREAD

**Issue by raghav9609** [essentiasoftserv/openbharatocr#41]
I have added 2 different PAN Card for OCR.  For img i have get all details but not for sumitpan.
![sumitpan](https://github.com/essentiasoftserv/openbharatocr/assets/151809587/55ab4b12-daec-4825-8bc4-737b935bcd48)
![img](https://github.com/essentiasoftserv/openbharatocr/assets/151809587/22a8d0bf-0305-4270-b60b-64cd384d8b63)

**Comment by nerdyk3** [comment]
we are working on it

**Comment by nerdyk3** [comment]
fixed in latest version
