### ISSUE TITLE
Birth certificate

### ISSUE THREAD

**Issue by nerdyk3** [essentiasoftserv/openbharatocr#44]
Requirements

- add a new function over the package that helps to parse birth certificate frontpage
the response will be in dict
- dict must be with name, address, dob, mother name, father name, registration name, registration date, 
Input
image of the front page

``` 
{
 "name":"",
"address":"",
"dob":"",
"mother name":"",
"father name ":"",
"registration number":"",
"registration date ":"",

}
```

**Comment by Rishabh0411** [comment]
Hi, I am working on it.
